ecomproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('delete_cart_item/<int:product_id>/',views.delete_cart_item,name='delete_cart_item'),
    path('ckeckout/',views.checkout,name='checkout'),
    path('',views.cart_detail,name='cart_detail'),

]

ecomproject/ecomapp/urls.py
from django.conf.urls.static import static

from . import views
from django.conf.urls.static import static
from django.urls import path
app_name='ecom'
urlpatterns = [


    path('', views.allprodcat, name='allprodcat'),
    path('<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proddetail, name='prodcatdetails'),

]

ecomproject/ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from ecomproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecomapp/', include('ecomapp.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomproject/search/urls.py
from django.urls import path
from . import views
app_name='search'
urlpatterns=[
    path('',views.searchRes,name='searchRes'),
]

ecomproject/cart/models.py
from django.db import models
from ecomapp.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price

    def __str__(self):
        return self.product

ecomproject/ecomapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    image=models.ImageField(upload_to='category',blank=True)
    desc=models.TextField(blank=True)
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('ecom:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    image=models.ImageField(upload_to='category',blank=True)
    desc=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    available=models.BooleanField(default=True)
    stock=models.IntegerField()
    created=models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def get_url(self):
        return reverse('ecom:prodcatdetails', args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.name)

ecomproject/search/models.py
from django.db import models

# Create your models here.

ecomproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecomapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def delete_cart_item(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)

    cart_item.delete()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += cart_item.product.price
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', {'cart_items': cart_items, 'total': total, 'counter': counter})

def checkout(request):
    return render(request,'checkout.html')

ecomproject/ecomapp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import EmptyPage,InvalidPage,Paginator

from .models import Category, Product


# Create your views here.
def home(request):
    return render(request, "base.html")


def allprodcat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,4)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': c_page, 'products': products})


def proddetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecomproject/search/views.py
from django.shortcuts import render
from ecomapp.models import Product
from django.db.models import Q


# Create your views here.
def searchRes(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

ecomproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <meta name="description" content="{% block metadescription %} {% endblock %}">


    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color:rgb(255,255,240);">
<div class="container">
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
    <br>
    <br>
<div>
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


</div>
</div>


</body>
</html>

ecomproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Lists for all your shopping needs Sign In Save time Add your items and ideas in one convenient location Give great gifts Remember your friends' lists and share yours Check price changes and stocks.
{% endblock %}
{% block title %}
WishList - Old Is Gold Pvt.Ltd
{% endblock %}
{% block content %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h2 class="text-center my_title">
            Add Your favorite ride to see the Wishlist
        </h2>
        <br>
        <button class="btn btn-outline-danger text-center" type="submit"><a href="{% url 'ecom:allprodcat' %}">ALL VEHICLES</a></button>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h2 class="text-center my_title">
            Your WishList
        </h2>
        <br>
    </div>
    <div class="row me-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="table_head">
                <tr>
                    <th colspan="5">
                        Your favorite vehicles

                    </th>
                </tr>
                </thead>
                <tbody>
                {% for i in cart_items %}
                <tr>
                    <td>
                        <a href="{{ i.product.get_url }}"><img src="{{i.product.image.url}}" alt="{{i.product.name}}" class="float-left rounded custom_image"> </a>

                    </td>
                    <td class="text-left">
                        {{i.product.name}}
                        <br>
                        SKU: {{i.product.id}}
                        <br>
                        PRICE: INR {{i.product.price}}
                        <br>
<!--                        Qty: {{i.quantity}}-->

                    </td>
                    <td>
                        TOTAL: {{i.sub_total}}
                    </td>
<!--                    {% if i.item.quantity < i.product.stock %}-->
<!--                    <td>-->
<!--                        <a href="{% url 'cart:add_cart' i.product.id %}" class="custom_a"><i class="fa fa-plus custom_plus"></i></a>-->
<!--                        &nbsp;<a href="" class="custom_a"><i class="fa fa-minus custom_plus"></i></a>-->
<!--                        &nbsp;<a href="" class="custom_plus"><i class="fa fa-trash custom_plus"></i></a>-->
<!--                    </td>-->
<!--                    {% else %}-->
<!--                                        <td>-->
<!--                        &nbsp;<a href="" class="custom_a"><i class="fa fa-minus custom_plus" aria-hidden="true"></i></a>-->
                    <td>
                    <a href="{% url 'cart:delete_cart_item' i.product.id %}" ><i class="material-icons">delete</i></a>
                    </td>
<!--                    {% endif %}-->
                </tr>
                {% endfor %}
                </tbody>

            </table>

        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="table_head">
                <tr>
                    <th>
                        CHECKOUT
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        please review your vehicle before proceeding payment

                    </td>

                </tr>
                <tr>
                    <td>
                        Your Total is : <strong>{{total}}</strong>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="{% url 'cart:checkout' %}" class="btn btn-primary">CHECKOUT</a>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecom:allprodcat' %}" class="btn btn-secondary btn-block my_custom_button">All Vehicles</a>
            </div>
        </div>

    </div>
</div>
{% endif %}
{% endblock %}

ecomproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
{{category.desc|truncatewords:155}}
{% else %}
welcome to Old Is Gold
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
{{category.name}} - Old Is Gold
{% else %}
Explore the world of vehicles
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx_auto">
        <h6><a  class="row my_row_class my_font" href="{% url 'ecom:allprodcat' %}"> Our vehicle collection</a> </h6>
    </div>
        </div>
</div>
{% endif %}

<div>
    <div class="mx_auto">

        {% if category %}
        <center>
        <img  src="{{category.image.url}}"alt="{{category.name}}" height="250" width="500">
            </center>
    </div>
    <br>
    <div>
        <h2 class="text-center my_title" >{{category.name}}</h2>
        <p class="text-justify">{{category.desc}}</p>
    </div>
    {% else %}
    <div>
        <center>
        <img  class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Explore vehicles" height="300" width="700">
            </center>
    </div>
    <br>
    <div>
        <center>
        <h2>Explore And book you dream ride</h2>
        <P class="text-justify my_font">Car is not limited to luxury items but it has taken over an important requirement in our lives. Need to go to the supermarket, need to go to your friend’s place, need to go to the doctor, need to go out for a hangout; the one-stop solution is CAR. It will take you to your destination without any hassle. It will provide you with coolness in summer & warmness in winter. In short, you will be amazed to know more about it once you start loving it. </P>
        <b class="my_font">Old is Gold - Everything is affordable</b>
        </center>
    </div>
    {% endif %}
</div>
<div>
    <center>
        <h4 class="my_font" >Our offers</h4>
    </center>
</div>
<div  class="container">
    <div class="row">
        {% for i in products.object_list %}
        <div class="my_bottom_margin  col-md-3" style="padding:20px;">
            <div class="card text-center" style="min-width:12rem;padding:10px;">
                <a href="{{i.get_url}}"><img class="card-image-top my_image" src="{{i.image.url}}" alt="{{i.name}}" height="200" width="200"> </a>

            <div class="card-body">
            <h4 class="my_font">{{i.name}}</h4>
            <p class="my_font">INR - {{i.price}}</p>

            </div>
            </div>
            </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecomproject/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Lists for all your shopping needs Sign In Save time Add your items and ideas in one convenient location Give great gifts Remember your friends' lists and share yours Check price changes and stocks.
{% endblock %}
{% block title %}
checkout page - Old Is Gold Pvt.Ltd
{% endblock %}
{% block content %}
<div class="text-center">
<h1 class="anime">congratzz you have purchased a beautiful vehicle </h1>
    </div>
{% endblock %}

ecomproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">$copy right@ oldisgold website </p>
</div>

ecomproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'ecom:allprodcat' %}"><img src="{% static 'img/logo.png' %}" alt="logoimage" height="200" width="200"></a>
    
  </center>
</header>

ecomproject/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-dark navbar sticky-top " style="background-color:black;">
  <div class="container-fluid">
    <a class="navbar-brand my_font" href="{% url 'ecom:allprodcat' %}">All Vehicles</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         {% for cat in links %}
        <li class="nav-item">
          <a class="nav-link active my_font" aria-current="page" href="{{cat.get_url}}">{{cat.name}}</a>
        </li>
        {% endfor %}
        <li class="nav-item">
          <a class="nav-link  my_font" href="{% url 'cart:cart_detail' %}" > WishList </a>
        </li>

      </ul>
      <form class="d-flex " action="{% url 'search:searchRes' %}" method="GET">
        {% csrf_token %}
        <input class="form-control me-2"  placeholder="Search"  name="q">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

ecomproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{% if product %}
{{product.name}} - Old Is Gold
{% else %}
Explore the world of vehicles
{% endif %}
{% endblock %}

{% block content %}

<!--<div>-->

<!--    <div>-->
<!--        <p><a href="{% url 'ecom:allprodcat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a> </p>-->
<!--    </div>-->
<!--</div>-->
<!--<br>-->
<div class="container">
    <div class="row">
<div class="col-12 col-sm-12 col-md-12 col-lg-6">


        <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>


<br>
        <br>
<br>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <h2>{{product.name}}</h2>
        <p>INR - {{product.price}}</p>
        <h5><i>Product Description:</i></h5>
        <p>{{product.desc}}</p>
                    {% if product.stock > 1 %}
            <h4><a  class=" btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Wishlist</a>  | <a class=" btn btn-secondary" href="{% url 'cart:checkout' %}">Buy Now</a> </h4>
            {% else %}
            <h2><b>This ride is Sold out</b></h2>
            {% endif %}
            </div>

</div>
    </div>






{% endblock %}

ecomproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
welcome to Old Is Gold. We have variety of stock conditioned vehicle as well as modified vehicles. All you want to do is search for your dream vehicle and buy.
{% endblock %}
{% block title %}
search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search">You have searched for : <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row">
        {% for i in products %}
        <div class="my_bottom_margin  col-md-3" style="padding:20px;">
            <div class="card text-center" style="min-width:12rem;padding:10px;">
                <a href="{{i.get_url}}"><img class="card-image-top my_image" src="{{i.image.url}}" alt="{{i.name}}" height="200" width="200"> </a>
            </div>
            <div class="card-body">
            <h4 class="my_font">{{i.name}}</h4>
            <p class="my_font">INR - {{i.price}}</p>

        </div>
            </div>

{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search">0 result found</p>
</div>
{% endfor %}
            </div>
</div>
{% endblock %}